
logging:
  level:
    root: INFO

server.port: 7001
 
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always 

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
    
  cloud:
    stream:
      bindings:
        input:
          destination: products
          content-type: application/json
          group: productsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

api:
  pagination:
    pageNumber: 0
    pageSize: 10
    
---
spring.profiles: docker

server.port: 8081

logging:
  level:
    '[com.me.work.example.microservices.core.product]': DEBUG
    '[com.me.work.example.handler.http]': DEBUG
    
spring:
  data:
    mongodb:
      host: mongodb
      database: productsdb
      port: 27017
      
  cloud:
    stream:
      default-binder: rabbit
      
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: michael
    password: jordan
    
---
spring.profiles: product-swagger

api:
  common:
    version: 1.0.0
    title: Product API
    description: The product API is an example for the API implementation
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Rudy SANIEZ
      url: https://github.com/rudysaniez
      email: rudysaniez@laposte.net
