
logging:
  level:
    root: INFO

server.port: 8081
 
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always 

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
    
  cloud:
    stream:
      bindings:
        input:
          destination: products
          content-type: application/json
          group: productsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
            
  data:
    mongodb:
      database: products_data

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

api:
  pagination:
    pageNumber: 0
    pageSize: 10
    
---
spring.profiles: docker

logging:
  level:
    '[com.me.work.example.microservices.core.product]': DEBUG
    '[com.me.work.example.handler.http]': DEBUG
    '[org.springframework.data.mongodb.core.MongoTemplate]': DEBUG

spring:
  data:
    mongodb:
      uri: mongodb+srv://${mongo-username}:${mongo-password}@${mongo-cluster}/${spring.data.mongodb.database}?retryWrites=true&w=majority

  cloud:
    stream:
      default-binder: rabbit

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: michael
    password: jordan
