
logging:
  level:
    root: INFO

server.port: 7001
 
spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
    default-property-inclusion: NON_NULL #permits to not return fields with null value.
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
    
---
spring.profiles: docker

server.port: 8081

logging:
  level:
    com.me.work.example.microservices.core.product: DEBUG
    com.me.work.example.handler.http: DEBUG
    
---
spring.profiles: product-swagger

api:

  application-name: Products API
  note: The products-api is an example for the API implementation.

  common:
    version: 1.0.0
    title: Products API
    description: The products-api is an example for the API implementation
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Rudy SANIEZ
      url: https://github.com/rudysaniez
      email: rudysaniez@laposte.net
