
version: "2.1"
  
services:
  
  mongodb:
    image: mongo:3.2.4
    container_name: mongodb
    mem_limit: 350m
    ports:
      - 27017:27017
    command: --smallfiles
  
  reviews-db:
    image: mysql:latest
    container_name: reviews-db
    mem_limit: 350m
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=welcome
      - MYSQL_USER=michael
      - MYSQL_PASSWORD=jordan
      - MYSQL_DATABASE=reviewsdb
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-umichael", "-pjordan", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    
  product:
    build: microservices/product-service
    mem_limit: 350M
    ports:
      - "9081:8081"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256M -Xmx256M
      
  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350M
    ports:
      - "9082:8082"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256M -Xmx256M
      
  review:
    build: microservices/review-service
    mem_limit: 350M
    ports:
      - "9083:8083"
    depends_on:
      reviews-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256M -Xmx256M
      
  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350M
    ports:
      - "9080:9080"
    depends_on:
      - product
      - recommendation
      - review
    environment:
      - SPRING_PROFILES_ACTIVE=docker,product-composite-swagger
      - JAVA_OPTS=-Xms256M -Xmx256M
