---
openapi: 3.0.1
info:
  title: Product-composite-api
  version: v0
  description: Product-composite REST API.
servers:
- url: http://localhost:9080/api/v1
  description: Generated server url
paths:
  /products-composite/{productId}:
    summary: Get and delete a product-composite.
    get:
      tags:
      - product-composite-service-impl
      parameters:
      - name: productId
        description: Product identifier.
        schema:
          format: int32
          type: integer
        in: path
        required: true
      - name: pageNumber
        description: Page number.
        schema:
          format: int32
          type: integer
        in: query
        required: false
      - name: pageSize
        description: Page size.
        schema:
          format: int32
          type: integer
        in: query
        required: false
      responses:
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductAggregate'
          description: OK
      operationId: getCompositeProduct
      summary: Get a product-composite.
    delete:
      tags:
      - product-composite-service-impl
      parameters:
      - name: productId
        description: Product identifier.
        schema:
          format: int32
          type: integer
        in: path
        required: true
      responses:
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "200":
          description: OK
      operationId: deleteCompositeProduct
      summary: Delete a product-composite.
    parameters:
    - name: productId
      description: Product identifier.
      schema:
        format: int32
        type: integer
      in: path
      required: true
  /products-composite:
    summary: Create a product-composite.
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductComposite'
        required: true
      tags:
      - product-composite-service-impl
      responses:
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductComposite'
          description: Created
      operationId: createCompositeProduct
      summary: Create a product-composite.
components:
  schemas:
    HttpErrorInfo:
      description: Error information.
      type: object
      properties:
        timestamp:
          format: date-time
          description: Temporal information.
          type: string
        path:
          description: Path reminder.
          type: string
        httpStatus:
          description: Http status.
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
          type: string
        message:
          description: Error message.
          type: string
    PageMetadata:
      description: Page information.
      type: object
      properties:
        size:
          format: int64
          description: Page size.
          type: integer
        totalElements:
          format: int64
          description: Total elements.
          type: integer
        totalPages:
          format: int64
          description: Total pages.
          type: integer
        number:
          format: int64
          description: Page number.
          type: integer
    PagedRecommendationSummary:
      description: Page of recommendations. The page informations is attached.
      type: object
      properties:
        content:
          description: Several recommendations.
          type: array
          items:
            $ref: '#/components/schemas/RecommendationSummary'
        page:
          $ref: '#/components/schemas/PageMetadata'
          description: Page information.
    PagedReviewSummary:
      description: Page of reviews. The page informations is attached.
      type: object
      properties:
        content:
          description: Several reviews.
          type: array
          items:
            $ref: '#/components/schemas/ReviewSummary'
        page:
          $ref: '#/components/schemas/PageMetadata'
          description: Page information.
    ProductAggregate:
      description: Product-aggregate for the product research. The recommendations
        and reviews are attached.
      type: object
      properties:
        productID:
          format: int32
          description: Product identifier.
          type: integer
        name:
          description: Product name.
          type: string
        weight:
          format: int32
          description: Weight.
          type: integer
        recommendations:
          $ref: '#/components/schemas/PagedRecommendationSummary'
          description: Recommendations.
        reviews:
          $ref: '#/components/schemas/PagedReviewSummary'
          description: Reviews.
    RecommendationSummary:
      description: Recommendation summary for the product-composite REST API.
      type: object
      properties:
        recommendationID:
          format: int32
          description: Recommendation identifier.
          type: integer
        author:
          description: Author.
          type: string
        rate:
          format: int32
          description: Rate.
          type: integer
        content:
          description: Content.
          type: string
    ReviewSummary:
      description: Review summary for the product-composite REST API.
      type: object
      properties:
        reviewID:
          format: int32
          description: Review identifier.
          type: integer
        author:
          description: Author.
          type: string
        subject:
          description: Subject.
          type: string
        content:
          description: Content.
          type: string
    ProductComposite:
      description: Product-composite for the product creation with recommendations
        and reviews attached.
      type: object
      properties:
        productID:
          format: int32
          description: Product identifier.
          type: integer
        name:
          description: Product name.
          type: string
        weight:
          format: int32
          description: Weight.
          type: integer
        recommendations:
          description: Recommendations.
          type: array
          items:
            $ref: '#/components/schemas/RecommendationSummary'
        reviews:
          description: Reviews.
          type: array
          items:
            $ref: '#/components/schemas/ReviewSummary'
