
server.port: 8082

logging:
  level:
    com.me.work.example.microservices.core.recommendation: DEBUG
    com.me.work.example.handler.http: DEBUG

---
spring.profiles: dev

spring:
  data:
    mongodb:
      host: localhost
      database: productsdb
      port: 27017