
logging:
  level:
    root: INFO

server.port: 8083

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  webflux:
    base-path: /api/v1

  cloud:
    stream:
      bindings:
        input:
          destination: reviews
          content-type: application/json
          group: reviewsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0

  data:
    mongodb:
      database: reviews_data

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

api:
  pagination:
    default-page-number: 0
    default-page-size: 10

---
spring.profiles: docker

logging:
  level:
    '[com.me.work.example.microservices.core.review]': DEBUG
    '[com.me.work.example.handler.http]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.cache]': DEBUG
    '[org.springframework.cache]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

spring:
  data:
    mongodb:
      uri: mongodb+srv://${mongo-username}:${mongo-password}@${mongo-cluster}/${spring.data.mongodb.database}?retryWrites=true&w=majority
    
  cloud:
    stream:
      default-binder: rabbit
      
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: michael
    password: jordan
