
logging:
  level:
    root: INFO

server.port: 7003
 
spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
    
---
spring.profiles: docker

server.port: 8083

logging:
  level:
    com.me.work.example.microservices.core.review: DEBUG
    com.me.work.example.handler.http: DEBUG
    
---
spring.profiles: review-swagger

api:
  common:
    version: 1.0.0
    title: Review API
    description: The review-api is an example for the API implementation
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Rudy SANIEZ
      url: https://github.com/rudysaniez
      email: rudysaniez@laposte.net
