
logging:
  level:
    root: INFO

server.port: 7003

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
    
  jpa:    
    hibernate:
      ddl-auto: none
      
    show-sql: false
    
    properties:
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
            
      hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      hibernate.javax.cache.uri: META-INF/ehcache.xml
      
      hibernate.generate_statistics: false
      hibernate.jdbc.wrap_result_sets: true
      hibernate.jdbc.batch_size: 20
      hibernate.default_batch_fetch_size: 4
  
  cache:
    jcache:
      config: classpath:META-INF/ehcache.xml
    
api:
  pagination:
    default-page-number: 0
    default-page-size: 10
    
---
spring.profiles: docker

server.port: 8083

logging:
  level:
    com.me.work.example.microservices.core.review: DEBUG
    com.me.work.example.handler.http: DEBUG
    
---
spring.profiles: review-swagger

api:
  common:
    version: 1.0.0
    title: Review API
    description: The review-api is an example for the API implementation
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Rudy SANIEZ
      url: https://github.com/rudysaniez
      email: rudysaniez@laposte.net
