
logging:
  level:
    root: INFO

server.port: 7003

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
  
  cloud:
    stream:
      bindings:
        input:
          destination: reviews
          content-type: application/json
          group: reviewsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
    
  jpa:    
    hibernate:
      #ddl-auto: update
      ddl-auto: none
      
    show-sql: false
    
    properties:
      '[hibernate.cache.use_query_cache]': true
      '[hibernate.cache.use_second_level_cache]': false
      '[hibernate.cache.region.factory_class]': org.hibernate.cache.jcache.internal.JCacheRegionFactory
            
      '[hibernate.javax.cache.provider]': org.ehcache.jsr107.EhcacheCachingProvider
      '[hibernate.javax.cache.uri]': META-INF/ehcache.xml
      
      '[hibernate.generate_statistics]': false
      '[hibernate.jdbc.wrap_result_sets]': true
      '[hibernate.jdbc.batch_size]': 20
      '[hibernate.default_batch_fetch_size]': 4
  
  cache:
    jcache:
      config: classpath:META-INF/ehcache.xml
    
api:
  pagination:
    default-page-number: 0
    default-page-size: 10
    
---
spring.profiles: docker

server.port: 8083

logging:
  level:
    '[com.me.work.example.microservices.core.review]': DEBUG
    '[com.me.work.example.handler.http]': DEBUG

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  datasource:
    url: jdbc:mysql://reviews-db:3306/reviewsdb?createDatabaseIfNotExist=true
    username: michael
    password: jordan
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  liquibase:
    change-log: classpath:liquibase/create-tables.xml
    default-schema: reviewsdb
    enabled: true
    
  cloud:
    stream:
      default-binder: rabbit
      
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: michael
    password: jordan

---
spring.profiles: review-swagger

api:
  common:
    version: 1.0.0
    title: Review API
    description: The review-api is an example for the API implementation
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Rudy SANIEZ
      url: https://github.com/rudysaniez
      email: rudysaniez@laposte.net
