
logging:
  level:
    root: INFO

server.port: 7000
 
app:
  product-service:
    host: localhost
    port: 7001
    
  recommendation-service:
    host: localhost
    port: 7002
    
  review-service:
    host: localhost
    port: 7003
 
spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
    default-property-inclusion: NON_NULL #permits to not return fields with null value.
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
    
---
spring.profiles: docker

server.port: 8081

app:
  product-service:
    host: product
    port: 8081
    
  recommendation-service:
    host: recommendation
    port: 8082
    
  review-service:
    host: review
    port: 8083

logging:
  level:
    com.me.work.example.microservices.core.composite: DEBUG
    com.me.work.example.handler.http: DEBUG
    