
logging:
  level:
    root: INFO

server.port: 9080
 
app:
  product-service:
    host: localhost
    port: 8081
    
  recommendation-service:
    host: localhost
    port: 8082
    
  review-service:
    host: localhost
    port: 8083
 
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL #permits to not return fields with null value.
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1
    
  cloud:
    stream:
      bindings:
        output-products:
          destination: products
          producer:
            required-groups: 
              - auditGroup
            
        output-recommendations:
          destination: recommendations
          producer:
            required-groups: 
              - auditGroup
            
        output-reviews:
          destination: reviews
          producer:
            required-groups:
              - auditGroup
              
api.pagination:
  page-number: 0
  page-size: 5
    
---
spring.profiles: docker

server.port: 9080

logging:
  level:
    '[com.me.work.example.microservices.core.composite]': DEBUG
    '[com.me.work.example.handler.http]': DEBUG
    
app:
  product-service:
    host: product
    port: 8081
    
  recommendation-service:
    host: recommendation
    port: 8082
    
  review-service:
    host: review
    port: 8083

spring:
  cloud:
    stream:
      default-binder: rabbit
      
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: michael
    password: jordan
