
version: "2.1"
  
services:

  product:
    build: .
    mem_limit: 350M
    ports:
      - 8081:8081
    depends_on: 
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker-api,docker-rabbit,product-swagger
      - JAVA_OPTS=-Xms512M -Xmx512M
      
  mongodb:
    image: mongo:3.6.9
    container_name: mongodb
    mem_limit: 350m
    ports:
      - 27017:27017
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10
      
  rabbitmq:
    image: rabbitmq:3.7.8-management
    mem_limit: 350m
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=michael
      - RABBITMQ_DEFAULT_PASS=jordan
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
