
logging:
  level:
    root: INFO
    '[com.me.work.example.microservices.core.product]': DEBUG
    '[com.me.work.example.handler.http]': DEBUG
    '[org.springframework.data.mongodb.core.MongoTemplate]': DEBUG
    
---
spring.profiles: dev

spring:
  data:
    mongodb:
      host: localhost
      database: productsdb
      port: 27017
      
  cloud:
    stream:
      default-binder: rabbit
      
  rabbitmq:
    host: localhost
    port: 5672
    username: michael
    password: jordan    
      
server.port: 8081
