
logging:
  level:
    root: INFO
    com.me.work.example.microservices.core.product: DEBUG
    com.me.work.example.handler.http: DEBUG
    
---
spring.profiles: dev

spring:
  data:
    mongodb:
      host: localhost
      database: productsdb
      port: 27017
      
server.port: 8081
