
logging:
  level:
    root: INFO
    com.me.work.example.microservices.core.composite: DEBUG
    com.me.work.example.handler.http: DEBUG
    
---
spring.profiles: dev

app:
  product-service:
    host: localhost
    port: 8081
    
  recommendation-service:
    host: localhost
    port: 8082
    
  review-service:
    host: localhost
    port: 8083

server.port: 9080